// Generated by utils/build_yt_preset.py from utils/yt-analysis.json.
// Measured onset-to-onset gaps; randomized order, not an exact replay.
const ytVideoPreset = {
  "label": "that YT video",
  "source_sha256": "1037e10424da483ebdebb7ca21a4ade603d84b6e814c1e98c6cac37c8a0a68ff",
  "settings": {
    "volume": 100,
    "minInterval": 0,
    "maxInterval": 944,
    "duration": 60,
    "overlap": 10,
    "speed": 100,
    "volVar": 0,
    "pitchVar": 0,
    "curve": "ytVideo",
    "strength": 100
  },
  "intervalsSeconds": [
    0.041708,
    0.125125,
    0.208542,
    0.333666,
    0.792459,
    1.75175,
    2.210541,
    2.25225,
    2.377375,
    68.485084,
    181.598104,
    315.857209,
    377.335292,
    762.863896,
    942.441479,
    943.150541
  ],
  "intervalScaleSeconds": 944,
  "notes": [
    "Resample measured gaps with replacement: preserves the empirical gap distribution, not the video sequence.",
    "Min interval zero enables overlapping sounds in the existing player.",
    "The first wait is sampled like any other; the video opens with a sound after about 1.4 seconds.",
    "Volume is an approximate mono RMS match; constant volume/speed are inferred from isolated copies.",
    "Matched events are estimates; unexplained audio in the source is not recreated."
  ]
};
