#!/usr/bin/env python3
"""Turn analyze_audio.py's measurements into the website's static preset data."""
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build(report):
    intervals = sorted(report['intervals_seconds'])
    if not intervals or any(not math.isfinite(x) or x <= 0 for x in intervals):
        raise ValueError('Expected positive finite onset-to-onset intervals.')
    maximum = math.ceil(max(intervals))
    comparison = report['reference_comparison']
    # Codec/phase differences are not evidence of deliberate randomization.
    # Round the approximate RMS comparison to the nearest five percentage points.
    settings = {
        'volume': max(5, round(comparison['rms_gain_percent'] / 5) * 5),
        'minInterval': 0, 'maxInterval': maximum,
        'duration': round(report['duration_seconds'] / 60),
        'overlap': 10, 'speed': round(comparison['speed_percent']),
        'volVar': 0, 'pitchVar': 0, 'curve': 'ytVideo', 'strength': 100
    }
    return {
        'label': 'that YT video', 'source_sha256': report['sha256'],
        'settings': settings, 'intervalsSeconds': intervals,
        'intervalScaleSeconds': maximum,
        'notes': [
            'Resample measured gaps with replacement: preserves the empirical gap distribution, not the video sequence.',
            'Min interval zero enables overlapping sounds in the existing player.',
            'The first wait is sampled like any other; the video opens with a sound after about 1.4 seconds.',
            'Volume is an approximate mono RMS match; constant volume/speed are inferred from isolated copies.',
            'Matched events are estimates; unexplained audio in the source is not recreated.'
        ]
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('report', nargs='?', type=Path, default=ROOT / 'utils/yt-analysis.json')
    parser.add_argument('--output', type=Path, default=ROOT / 'yt-preset.js')
    parser.add_argument('--json-output', type=Path, default=ROOT / 'utils/yt-preset.json')
    args = parser.parse_args()
    data = build(json.loads(args.report.read_text()))
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(data, indent=2) + '\n')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        '// Generated by utils/build_yt_preset.py from utils/yt-analysis.json.\n'
        '// Measured onset-to-onset gaps; randomized order, not an exact replay.\n'
        'const ytVideoPreset = ' + json.dumps(data, indent=2) + ';\n')
    print(json.dumps(data['settings'], indent=2))
    print(f'Wrote {args.output} and {args.json_output}')


if __name__ == '__main__':
    main()
